# GitHub Pages Configuration for NTUT CSIE Campus Guide

# Theme
theme: jekyll-theme-cayman

# Site settings
title: "北科資工系 - 校園導覽專案"
description: "國立臺北科技大學資訊工程系校園互動導覽系統"
author: "NTUT CSIE Students"

# GitHub repository info
github:
  repository_name: "NTUT_CSIE"
  repository_url: "https://github.com/username/NTUT_CSIE"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
lang: zh-TW
locale: zh_TW

# Navigation
show_downloads: false

# Custom variables
campus_name: "國立臺北科技大學"
department: "資訊工程系"

# Exclude files from processing
exclude:
  - README_dev.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor